# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\template\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Game
  module Docs
    module A_GETTING_STARTED
      # # Starter Game Architecture & Overview
      #
      # Welcome to your new Lapis game project! This template demonstrates a complete, standalone
      # Crystal game powered by Godot 4. It includes 3D player movement physics, UI HUD signal bindings,
      # custom gameplay nodes, automated specs, and performance benchmarks.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Game Architecture & Main Scene</strong></td>
      #       <td><code>.topic_01_game_architecture</code></td>
      #       <td>The root scene controller and scene lifecycle in Lapis.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Project Directory Structure</strong></td>
      #       <td><code>.topic_02_directory_layout</code></td>
      #       <td>Understanding the role of each directory in your Lapis game.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/main.cr
      # - src/player_controller.cr
      # - src/game_hud.cr
      #
      module A_OVERVIEW
        # **Game Architecture & Main Scene**: The root scene controller and scene lifecycle in Lapis.
        #
        # The entry point for gameplay is defined in `src/main.cr` via `MainNode < Node3D`.
        # When Godot loads `scenes/main.tscn`:
        #
        # 1. `MainNode#_ready` executes, printing welcome diagnostics to the console.
        # 2. It dynamically locates child nodes (`Player` and `HUD`).
        # 3. It connects the `PlayerController#health_changed` signal to `GameHUD#update_health`.
        # 4. It emits the `initialized` signal to notify any listening subsystems.
        #
        # #### Working Examples
        #
        # ```crystal
        # # Inside src/main.cr:
        # node MainNode < Node3D do
        #   signal initialized
        #
        #   onready? player, PlayerController, "Player"
        #   onready? hud, GameHUD, "HUD"
        #
        #   def _ready : Void
        #     Godot.print("Starting Lapis Starter Game...")
        #     if (p = player) && (h = hud)
        #       p.health_changed.connect do |curr, max_hp|
        #         h.update_health(curr, max_hp)
        #       end
        #     end
        #     emit(initialized)
        #   end
        # end
        # ```
        #
        def self.topic_01_game_architecture : Nil; end

        # **Project Directory Structure**: Understanding the role of each directory in your Lapis game.
        #
        # - `src/`: Crystal gameplay code (`main.cr`, nodes, components).
        # - `scenes/`: Godot `.tscn` scene files.
        # - `scripts/`: Optional GDScript fixtures or interop nodes.
        # - `spec/`: Automated Crystal unit specs and in-editor test suites.
        # - `benchmarks/`: Performance benchmarks measuring Crystal execution speeds.
        # - `docs_src/`: YAML documentation files compiled into HTML API docs via `make docs`.
        # - `bin/`: Compiled DLLs and standalone game executables.
        #
        def self.topic_02_directory_layout : Nil; end
      end
    end
  end
end
{% end %}
