# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\template\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Game
  module Docs
    module A_GETTING_STARTED
      # # Gameplay Systems & Player Controller
      #
      # The starter game includes a working 3D player character (`PlayerController < CharacterBody3D`)
      # and a corresponding 2D interface HUD (`GameHUD < Control`) demonstrating signal connections,
      # smooth physics movement, and inspector properties.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Player Physics & Movement</strong></td>
      #       <td><code>.topic_01_player_movement</code></td>
      #       <td>Handling velocity, jumping, gravity, and WASD input in _physics_process.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>GameHUD UI & Signal Handling</strong></td>
      #       <td><code>.topic_02_hud_and_signals</code></td>
      #       <td>UpdatingProgressBar health meters and text labels in response to gameplay signals.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/player_controller.cr
      # - src/game_hud.cr
      #
      module B_GAMEPLAY_SYSTEMS
        # **Player Physics & Movement**: Handling velocity, jumping, gravity, and WASD input in _physics_process.
        #
        # `PlayerController` extends Godot's `CharacterBody3D`:
        #
        # - Reads standard input actions: `ui_left`, `ui_right`, `ui_up`, `ui_down`, and `ui_accept`.
        # - Applies gravity when `!is_on_floor`.
        # - Updates `velocity` and dispatches `move_and_slide`.
        # - Tracks hit points and emits the `health_changed(current : Int32, max_hp : Int32)` signal.
        #
        # #### Working Examples
        #
        # ```crystal
        # node PlayerController < CharacterBody3D do
        #   @[Export(range: 1.0_f32..20.0_f32, step: 0.5_f32)]
        #   property speed : Float32 = 5.0_f32
        #
        #   signal health_changed(current : Int32, max_health : Int32)
        #
        #   def _physics_process(delta : Float64) : Void
        #     # Movement and physics logic
        #   end
        # end
        # ```
        #
        def self.topic_01_player_movement : Nil; end

        # **GameHUD UI & Signal Handling**: UpdatingProgressBar health meters and text labels in response to gameplay signals.
        #
        # The `GameHUD` node extends `Control` and listens for signals emitted by the player:
        #
        # ```crystal
        # node GameHUD < Control do
        #   def update_health(current : Int32, max_hp : Int32) : Void
        #     percentage = (current.to_f32 / max_hp.to_f32) * 100.0_f32
        #     Godot.print("[HUD] Player health updated: #{percentage.round}%")
        #   end
        # end
        # ```
        #
        def self.topic_02_hud_and_signals : Nil; end
      end
    end
  end
end
{% end %}
