# ==============================================================================
# Game::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Game
  # The `Game::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 1 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_OVERVIEW</code></td>
  #       <td><strong>Starter Game Architecture & Overview</strong></td>
  #       <td>Overview of your standalone Lapis game architecture, node hierarchy, and scene organization.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_GAMEPLAY_SYSTEMS</code></td>
  #       <td><strong>Gameplay Systems & Player Controller</strong></td>
  #       <td>How player input, physics movement, health tracking, and HUD signals are structured.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Game Quick Start:
    # ```bash
    # make docs        # Build offline HTML documentation site in docs/
    # make test        # Execute specifications and test suites
    # make all         # Build and verify all targets
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::A_OVERVIEW`: **Starter Game Architecture & Overview** &mdash; Overview of your standalone Lapis game architecture, node hierarchy, and scene organization.
    # - `A_GETTING_STARTED::B_GAMEPLAY_SYSTEMS`: **Gameplay Systems & Player Controller** &mdash; How player input, physics movement, health tracking, and HUD signals are structured.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::A_OVERVIEW`: **Starter Game Architecture & Overview** &mdash; Overview of your standalone Lapis game architecture, node hierarchy, and scene organization.
    # - `A_GETTING_STARTED::B_GAMEPLAY_SYSTEMS`: **Gameplay Systems & Player Controller** &mdash; How player input, physics movement, health tracking, and HUD signals are structured.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/a_overview"
require "./docs/a_getting_started/b_gameplay_systems"
{% end %}
